- hosts: all
  become: true
  tasks:
    - name: Install required system packages
      apt:
        pkg:
          - python3
          - python3-venv
          - npm
          - nodejs
          - git
        state: latest
        update_cache: true
